name: Dumbo
main: science.amberfall.dumbo.Dumbo
version: 1.2.2
author: Sweepyoface
website: https://github.com/Sweepyoface/dumbo-bukkit/
commands:
  dumbo:
    description: Get a random Qball quote.
    usage: /dumbo
  dumbo reload:
      description: Reload the Dumbo config.
      usage: /dumbo reload
  
permissions:
   dumbo.quote:
    description: /dumbo command
    default: op
   dumbo.reload:
    description: /dumbo reload command
    default: op